---
abstract: "IDOPEREL's plugin bundle for Dist::Zilla."
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102343, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-IDOPEREL
requires:
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::DistManifestTests: 0
  Dist::Zilla::Plugin::GithubMeta: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MinimumPerl: 0
  Dist::Zilla::Plugin::NextRelease: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::PluginBundle::Classic: 0
  Dist::Zilla::PluginBundle::Filter: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle: 0
  Moose: 0
  Moose::Autobox: 0
  namespace::autoclean: 0
  perl: 5.004
resources:
  homepage: http://github.com/ido50/Dist-Zilla-PluginBundle-IDOPEREL/tree
  repository: git://github.com/ido50/Dist-Zilla-PluginBundle-IDOPEREL.git
version: 0.3
