---
abstract: "IDOPEREL's plugin bundle for Dist::Zilla."
author:
  - 'Ido Perlmuter <ido@ido50.net>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102160'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-IDOPEREL
requires:
  Dist::Zilla::Plugin::AutoPrereqs: 4.200000
  Dist::Zilla::Plugin::CheckChangesHasContent: 0.003
  Dist::Zilla::Plugin::DistManifestTests: 1.101420
  Dist::Zilla::Plugin::GithubMeta: 0.10
  Dist::Zilla::Plugin::LatestPrereqs: 0.3
  Dist::Zilla::Plugin::MetaJSON: 4.200000
  Dist::Zilla::Plugin::MinimumPerl: 0.02
  Dist::Zilla::Plugin::NextRelease: 4.200000
  Dist::Zilla::Plugin::ReadmeFromPod: 0.14
  Dist::Zilla::Plugin::TestRelease: 4.200000
  Dist::Zilla::PluginBundle::Classic: 4.200000
  Dist::Zilla::PluginBundle::Filter: 4.200000
  Dist::Zilla::PluginBundle::Git: 1.103520
  Dist::Zilla::Role::PluginBundle: 4.200000
  Moose: 1.21
  Moose::Autobox: 0.11
  namespace::autoclean: 0.11
  perl: 5.004
resources:
  homepage: http://github.com/ido50/Dist-Zilla-PluginBundle-IDOPEREL/tree
  repository: git://github.com/ido50/Dist-Zilla-PluginBundle-IDOPEREL.git
version: 0.4
